src/Entity/Author.php
<?php

namespace App\Entity;

use App\Repository\AuthorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use function sprintf;

/**
 * @ORM\Entity(repositoryClass=AuthorRepository::class)
 */
class Author
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $middleName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @ORM\ManyToMany(targetEntity=Book::class, mappedBy="authors")
     */
    private $books;

    /**
     * @ORM\OneToOne (targetEntity=Address::class, cascade={"persist", "remove"})
     */
    private $address;

    public function __construct()
    {
        $this->books = new ArrayCollection();
        $this->address = new Address();
    }

    public function __toString()
    {
        return $this->getFullName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getMiddleName(): ?string
    {
        return $this->middleName;
    }

    public function setMiddleName(?string $middleName): self
    {
        $this->middleName = $middleName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFullName(): string
    {
        return sprintf(
            '%s %s %s',
            $this->firstName,
            $this->middleName,
            $this->lastName
        );
    }

    /**
     * @return Collection|Book[]
     */
    public function getBooks(): Collection
    {
        return $this->books;
    }

    public function addBook(Book $book): self
    {
        if (!$this->books->contains($book)) {
            $this->books[] = $book;
            $book->addAuthor($this);
        }

        return $this;
    }

    public function removeBook(Book $book): self
    {
        if ($this->books->contains($book)) {
            $this->books->removeElement($book);
            $book->removeAuthor($this);
        }

        return $this;
    }

    public function getAddress(): Address
    {
        return $this->address;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
            <style>
                html {text-align: center; font-family: Verdana,Geneva,sans-serif}
                body {width: 75%; margin:50px auto 50px auto; text-align: left}
                h1 {width: 100%; text-align:center}
                .button {
                    font-size: 100%;
                    padding: .5em 1em;
                    color: rgba(0,0,0,.8);
                    border: transparent;
                    background-color: #e6e6e6;
                    text-decoration: none;
                    border-radius: 2px;
                }
                table {
                    border-collapse: collapse;
                    width: 100%;
                }

                td, th {
                    border: 1px solid #dddddd;
                    text-align: left;
                    padding: 8px;
                }

                tr:nth-child(even) {
                    background-color: #dddddd;
                }
                .underline {text-decoration: underline}
                .label {font-weight:600;}
                .grid {display:grid}
                .grid {
                    grid-template-columns: 25% 75%;
                    grid-row-gap: 30px;
                }
                .graybox {background-color:lightgray; padding:20px;}
            </style>
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
        {% block body %}
            <h2 class="underline">What do you want to do?</h2>
            <div class="graybox"><a class="button" href="{{ path('list_publisher') }}">Go to publishers</a></div>
            <div class="graybox"><a class="button" href="{{ path('list_author') }}">Go to authors</a></div>
            <div class="graybox"><a class="button" href="{{ path('list_book') }}">Go to books</a></div>
        {% endblock %}
    </body>
</html>

templates/create_author.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <a href="{{ path('index') }}">Home</a>
    <br />
    <br />
    <br />
    {{ form_start(form) }}
    <div class="grid">
        <div class="label">{{ form_label(form.firstName) }}</div>
        <div>
            {{ form_widget(form.firstName) }}
            {{ form_errors(form.firstName) }}
        </div>

        <div class="label">{{ form_label(form.middleName) }}</div>
        <div>
            {{ form_widget(form.middleName) }}
            {{ form_errors(form.middleName) }}
        </div>

        <div class="label">{{ form_label(form.lastName) }}</div>
        <div>
            {{ form_widget(form.lastName) }}
            {{ form_errors(form.lastName) }}
        </div>

        <div class="label">{{ form_label(form.address) }}</div>
        <div>
            {{ form_errors(form.address.street) }}
            {{ form_widget(form.address.street) }}
        </div>
        <div class="label"></div>
        <div>
            <button>Submit</button>
        </div>
    </div>
    {{ form_end(form) }}
{% endblock body %}

templates/create_book.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <a href="{{ path('index') }}">Home</a>
    <br />
    <br />
    <br />
    {{ form_start(form) }}
    <div class="grid">
        <div class="label">{{ form_label(form.isbn) }}</div>
        <div>
            {{ form_widget(form.isbn) }}
            {{ form_errors(form.isbn) }}
        </div>

        <div class="label">{{ form_label(form.title) }}</div>
        <div>
            {{ form_widget(form.title) }}
            {{ form_errors(form.title) }}
        </div>

        <div class="label">{{ form_label(form.price) }}</div>
        <div>
            {{ form_widget(form.price) }}
            {{ form_errors(form.price) }}
        </div>

        <div class="label">{{ form_label(form.publisher) }}</div>
        <div>
            {{ form_widget(form.publisher) }}
            {{ form_errors(form.publisher) }}
        </div>

        <div class="label">{{ form_label(form.authors) }}</div>
        <div>
            {{ form_widget(form.authors) }}
            {{ form_errors(form.authors) }}
        </div>

        <div class="label"></div>
        <div>
            <button>Submit</button>
        </div>
    </div>
    {{ form_end(form) }}
{% endblock body %}

templates/create_publisher.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <a href="{{ path('index') }}">Home</a>
    <br />
    <br />
    <br />
    {{ form_start(form) }}
    <div class="grid">
        <div class="label">{{ form_label(form.name) }}</div>
        <div>
            {{ form_widget(form.name) }}
            {{ form_errors(form.name) }}
        </div>

        <div class="label"></div>
        <div>
            <button>Submit</button>
        </div>
    </div>
    {{ form_end(form) }}
{% endblock body %}

templates/list_author.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h2 class="underline">Authors</h2>
    <a class="button" href="{{ path('create_author') }}">+ Add new</a>
    <br />
    <br />
    <table>
        <tr>
            <th>Full name</th>
            <th>Address</th>
            <th></th>
        </tr>
        {% for author in data %}
            <tr>
                <td>{{ author.fullName }}</td>
                <td>{{ author.address.street }}</td>
                <td>
                    <a href="{{ path('edit_author', {id: author.id}) }}">edit</a>
                    <a href="{{ path('remove_author', {id: author.id}) }}">delete</a>
                </td>
            </tr>
        {% endfor %}
    </table>
    <br />
    <a href="{{ path('index') }}">Home</a>
{% endblock %}

templates/list_book.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h2 class="underline">Books</h2>
    <a class="button" href="{{ path('create_book') }}">+ Add new</a>
    <br />
    <br />
    <table>
        <tr>
            <th>ISBN</th>
            <th>Price</th>
            <th>Title</th>
            <th>Publisher</th>
            <th>Authors</th>
            <th>History</th>
            <th></th>
        </tr>
        {% for book in data %}
            <tr>
                <td>{{ book.isbn }}</td>
                <td>{{ book.price }}</td>
                <td>{{ book.title }}</td>
                <td>{{ book.publisher.name }}</td>
                <td>
                    {% for author in book.authors %}
                        {{ author.fullName }}{% if not loop.last %},{% endif %}
                    {% endfor %}
                </td>
                <td>
                    <a href="{{ path('list_price_history', {id: book.isbn}) }}">show</a>
                </td>
                <td>
                    <a href="{{ path('edit_book', {id: book.isbn}) }}">edit</a>
                    <a href="{{ path('remove_book', {id: book.isbn}) }}">delete</a>
                </td>
            </tr>
        {% endfor %}
    </table>
    <br />
    <a href="{{ path('index') }}">Home</a>
{% endblock %}

templates/list_price_history.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h2 class="underline">Price changes</h2>
    <table>
        <tr>
            <th>Book</th>
            <th>Price</th>
            <th>Changed</th>
        </tr>
        {% for change in data %}
            <tr>
                <td>{{ change.book.title }}</td>
                <td>{{ change.price }}</td>
                <td>{{ change.createdAt|date }}</td>
            </tr>
        {% endfor %}
    </table>
    <br />
    <a href="{{ path('list_book') }}">Back</a>
{% endblock %}

templates/list_publisher.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h2 class="underline">Publishers</h2>
    <a class="button" href="{{ path('create_publisher') }}">+ Add new</a>
    <br />
    <br />
    <table>
        <tr>
            <th>Name</th>
            <th></th>
        </tr>
        {% for publisher in data %}
            <tr>
                <td>{{ publisher.name }}</td>
                <td>
                    <a href="{{ path('edit_publisher', {id: publisher.id}) }}">edit</a>
                    <a href="{{ path('remove_publisher', {id: publisher.id}) }}">delete</a>
                </td>
            </tr>
        {% endfor %}
    </table>
    <br />
    <a href="{{ path('index') }}">Home</a>
{% endblock %}